In [5]:
%pip install pandas numpy matplotlib --quiet

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
# Import necessary libraries
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%config InlineBackend.figure_format = 'svg'

print("Libraries imported successfully!")

# Connect to the SQLite database
conn = sqlite3.connect("inventory.db")

# Create a cursor object to interact with the database
cursor = conn.cursor()

# Function to run a SQL query and return the results as a DataFrame
def run_query_to_df(cursor, query):
    cursor.execute(query)
    rows = cursor.fetchall()
    
    # Get column names from cursor
    columns = []
    for col in cursor.description:
        columns.append(col[0])

    # Convert to DataFrame
    df = pd.DataFrame(rows, columns = columns)

    return df

Libraries imported successfully!

In [7]:
query1 = """
SELECT shipping_mode,
    (SELECT COUNT("id") FROM shipping
    WHERE "delivery_status" = "Late delivery" AND shipping_mode = 'First Class')*100.0
    /(SELECT COUNT("id") FROM shipping
    WHERE shipping_mode = 'First Class')*1.0
AS "Late Rate"
FROM shipping
GROUP BY shipping_mode
HAVING shipping_mode = 'First Class'
"""

df1 = run_query_to_df(cursor, query1)

query2 = """
SELECT shipping_mode,
    (SELECT COUNT("id") FROM shipping
    WHERE "delivery_status" = "Late delivery" AND shipping_mode = 'Same Day')*100.0
    /(SELECT COUNT("id") FROM shipping
    WHERE shipping_mode = 'Same Day')*1.0
AS "Late Rate"
FROM shipping
GROUP BY shipping_mode
HAVING shipping_mode = 'Same Day'
"""

df2 = run_query_to_df(cursor, query2)

query3 = """
SELECT shipping_mode,
    (SELECT COUNT("id") FROM shipping
    WHERE "delivery_status" = "Late delivery" AND shipping_mode = 'Second Class')*100.0
    /(SELECT COUNT("id") FROM shipping
    WHERE shipping_mode = 'Second Class')*1.0
AS "Late Rate"
FROM shipping
GROUP BY shipping_mode
HAVING shipping_mode = 'Second Class'
"""

df3 = run_query_to_df(cursor, query3)

query4 = """
SELECT shipping_mode,
    (SELECT COUNT("id") FROM shipping
    WHERE "delivery_status" = "Late delivery" AND shipping_mode = 'Standard Class')*100.0
    /(SELECT COUNT("id") FROM shipping
    WHERE shipping_mode = 'Standard Class')*1.0
AS "Late Rate"
FROM shipping
GROUP BY shipping_mode
HAVING shipping_mode = 'Standard Class'
"""

df4 = run_query_to_df(cursor, query4)

combined_df = pd.concat([df1, df2, df3, df4], ignore_index=True)
combined_df

    shipping_mode  Late Rate
0     First Class  95.253813
1        Same Day  45.650773
2    Second Class  76.680446
3  Standard Class  38.137543

In [8]:
query = """
SELECT shipping_mode,
    (SELECT COUNT("id") FROM shipping
    WHERE "delivery_status" = "Late delivery" AND shipping_mode = 'Same Day')*100.0
    /(SELECT COUNT("id") FROM shipping
    WHERE shipping_mode = 'Same Day')*1.0
AS "Late Rate"
FROM shipping
GROUP BY shipping_mode
HAVING shipping_mode = 'Same Day'
"""

# Call the function to run the query and display results
result = run_query_to_df(cursor, query)
result

  shipping_mode  Late Rate
0      Same Day  45.650773

In [9]:
query = """
SELECT shipping_mode,
    (SELECT COUNT("id") FROM shipping
    WHERE "delivery_status" = "Late delivery" AND shipping_mode = 'Second Class')*100.0
    /(SELECT COUNT("id") FROM shipping
    WHERE shipping_mode = 'Second Class')*1.0
AS "Late Rate"
FROM shipping
GROUP BY shipping_mode
HAVING shipping_mode = 'Second Class'
"""

# Call the function to run the query and display results
result = run_query_to_df(cursor, query)
result

  shipping_mode  Late Rate
0  Second Class  76.680446

In [10]:
query = """
SELECT shipping_mode,
    (SELECT COUNT("id") FROM shipping
    WHERE "delivery_status" = "Late delivery" AND shipping_mode = 'Standard Class')*100.0
    /(SELECT COUNT("id") FROM shipping
    WHERE shipping_mode = 'Standard Class')*1.0
AS "Late Rate"
FROM shipping
GROUP BY shipping_mode
HAVING shipping_mode = 'Standard Class'
"""

# Call the function to run the query and display results
result = run_query_to_df(cursor, query)
result

    shipping_mode  Late Rate
0  Standard Class  38.137543